labels:
  - name: "good first issue"
    description: "Good for newcomers"
    color: "9a4f10"
  - name: "kind/bug"
    description: "+ BUG"
    color: "d876e3"
  - name: "kind/discussion"
    description: "Fetch information and discuss solution"
    color: "d876e3"
  - name: "kind/docs"
    description: "+ DOCS"
    color: "d876e3"
  - name: "kind/feature"
    description: "+ FEATURE"
    color: "d876e3"
  - name: "kind/improvement"
    description: "+ IMPROVEMENT"
    color: "d876e3"
  - name: "kind/tests"
    description: "Code tests to test code"
    color: "d876e3"
  - name: "service/api"
    description: "-- Service: API"
    color: "0e8a16"
  - name: "service/frontend"
    description: "-- Service: frontend"
    color: "0e8a16"
  - name: "service/ops"
    description: "-- Service: ops"
    color: "0e8a16"
  - name: "status/blocked"
    description: "Block! Further information is required"
    color: "ffffff"
  - name: "status/duplicate"
    description: "[ALREADY EXISTS]"
    color: "ffffff"
  - name: "status/wontfix"
    description: "This will not be worked on"
    color: "ffffff"
