version: '3.8'
services:
  bookit-api:
    container_name: bookit-api
    build: ./api
    restart: on-failure
    depends_on:
      - bookit-database
    env_file:
      - .env
    volumes:
      - ${PWD}/api:/python-docker
    ports:
      - 8181:5000
    networks:
      - database-network
      - default
  website:
    container_name: website
    build: ./frontend
    depends_on:
      - bookit-api
    env_file:
      - .env
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - default
  bookit-database:
    container_name: bookit-database
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 10s
    env_file:
      - .env
#    ports:
#      - 3306:3306
    volumes:
        - "dbdata:/var/lib/mysql:rw"
    networks:
      - database-network
      - default
networks:
  database-network:
    name: bookit-network
    driver: bridge
volumes:
  dbdata:
    driver: local